# Generated by Django 5.1.6 on 2025-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Stripe Price ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Stripe Product ID'),
        ),
    ]
