# Generated by Django 5.1.6 on 2025-02-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_id',
        ),
    ]
