# Generated by Django 5.1.6 on 2025-02-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_recipient_order_status_order_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='house',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
