# Generated by Django 5.1.6 on 2025-02-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_recipient_house_recipient_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
    ]
